-- Migration 078: Missing performance indexes for core query paths
-- Generated by system audit

-- 1. Scan results: segment + score filtering for screener / top lists
CREATE INDEX IF NOT EXISTS idx_scan_results_segment_score
  ON scan_results (segment, score_total DESC NULLS LAST);

-- 2. Scan results: sector + score filtering
CREATE INDEX IF NOT EXISTS idx_scan_results_sector_score
  ON scan_results (sector, score_total DESC NULLS LAST);

-- 3. Insider trades: ticker + trade_date lookup
CREATE INDEX IF NOT EXISTS idx_insider_trades_ticker_date
  ON insider_trades (ticker, trade_date DESC);

-- 4. Portfolio holdings: portfolio_id foreign key lookups
CREATE INDEX IF NOT EXISTS idx_holdings_portfolio_id
  ON holdings (portfolio_id);

-- 5. Paper trading: portfolio_id foreign key lookups
CREATE INDEX IF NOT EXISTS idx_paper_positions_portfolio_id
  ON paper_positions (portfolio_id);

CREATE INDEX IF NOT EXISTS idx_paper_trades_portfolio_id
  ON paper_trades (portfolio_id, traded_at DESC);

-- 6. Portfolio snapshots: user_id + date lookups
CREATE INDEX IF NOT EXISTS idx_portfolio_snapshots_user_date
  ON portfolio_snapshots (user_id, date DESC);

-- 7. AI journal: ticker + timestamp history lookup
CREATE INDEX IF NOT EXISTS idx_ai_journal_ticker_created
  ON ai_journal (ticker, created_at DESC);

-- 8. Price alerts: user_id lookup
CREATE INDEX IF NOT EXISTS idx_price_alerts_user_id
  ON price_alerts (user_id);

-- 9. Saved screens: user_id lookup
CREATE INDEX IF NOT EXISTS idx_saved_screens_user_id
  ON saved_screens (user_id);

-- 10. Strategy runs: user_id lookup
CREATE INDEX IF NOT EXISTS idx_strategy_runs_user_id
  ON strategy_runs (user_id, created_at DESC);
